### ISSUE TITLE
ros1 ros_comm that publishes/subscribes straight to zenoh

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_one2z#7]
Try this in rospy first, make a https://github.com/lucasw/ros_comm branch

**Comment by lucasw** [comment]
Sending this many bytes inside the ros_comm publish():

```rosrun ros1_example_pkg generate_image.py
...
put 691248 bytes on 'image'
```

but only expect this many
```
360 * 640 * 3
691200
```

The ros_comm publish is adding 48 additional bytes


Or even more?
```
[I] [1700948932.447 /zenoh_image_sub ...ts/./zenoh_image_to_contour.py:  42]: encoding: 'application/octet-stream' image PUT 777648
[E] [1700948932.452 /zenoh_image_sub ...sr/lib/python3.11/threading.py: 995]: Characters replaced when decoding message sensor_msgs/Image (will print only once): 'utf-8' codec can't decode byte 0xe0 in position 7: invalid continuation byte
Exception in thread Thread-5 (readqueue):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sensor_msgs/msg/_Image.py", line 168, in deserialize
    (_x.height, _x.width,) = _get_struct_2I().unpack(str[start:end])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 8 bytes
```

but in zenoh_image_to_contour receiving `691248`

**Comment by lucasw** [comment]
http://wiki.ros.org/ROS/Connection%20Header - this supplies the message type and definition, follow the tcpros thread to see how it is shared

**Comment by lucasw** [comment]
Now implement the subscriber side- this is a little less straight forward because of the callbacks, need to duplicate what `tcpros_pubsub.py` is doing or modify it.

rospy topics.py Subscriber has `receive_callback` called with message (already deserialized?).

**Comment by lucasw** [comment]
Also modify rostopic echo, store the message definitions somewhere in can get so this can be avoided:

```
rostopic echo /foo_bar
ERROR: Cannot load message class for [foo/Bar]. Are your messages built?
```

**Comment by lucasw** [comment]
roscpp C++ TopicManager looks like the easiest place to put a `zenohc::Session`

**Comment by lucasw** [comment]
Putting #include <zenohc.hxx> in topic manager.h results in this:

```
Errors     << roscpp:make /home/lucasw/ros/ros1_zenoh/logs/roscpp/build.make.089.log                                                                                                                                                    
/usr/bin/ld: CMakeFiles/roscpp.dir/src/libros/publisher.cpp.o: in function `zenohc::Publisher::get_keyexpr() const':
publisher.cpp:(.text+0x780): multiple definition of `zenohc::Publisher::get_keyexpr() const'; CMakeFiles/roscpp.dir/src/libros/subscriber.cpp.o:subscriber.cpp:(.text+0x780): first defined here
/usr/bin/ld: CMakeFiles/roscpp.dir/src/libros/publisher.cpp.o: in function `zenohc::Subscriber::get_keyexpr() const':
publisher.cpp:(.text+0x7f0): multiple definition of `zenohc::Subscriber::get_keyexpr() const'; CMakeFiles/roscpp.dir/src/libros/subscriber.cpp.o:subscriber.cpp:(.text+0x7f0): first defined here
/usr/bin/ld: CMakeFiles/roscpp.dir/src/libros/topic_manager.cpp.o: in function `zenohc::Publisher::get_keyexpr() const':
topic_manager.cpp:(.text+0xbe0): multiple definition of `zenohc::Publisher::get_keyexpr() const'; CMakeFiles/roscpp.dir/src/libros/subscriber.cpp.o:subscriber.cpp:(.text+0x780): first defined here
/usr/bin/ld: CMakeFiles/roscpp.dir/src/libros/topic_manager.cpp.o: in function `zenohc::Subscriber::get_keyexpr() const':
...
```

It works in the cpp files but then I have trouble with templated functions to serialize messages

**Comment by lucasw** [comment]
Can't do this, need to use zenohc?

```
namespace zenoh {
class ShmManager;
class Session;
};
```

````
/home/lucasw/other/install/include/zenoh.hxx:29:25: error: ‘namespace zenoh = zenohc;’ conflicts with a previous declaration
   29 | namespace zenoh = zenohc;
      |                         ^
```

**Comment by lucasw** [comment]
Maybe this is the root of the problem, in api.hxx
```
// Do not add '#pragma once' and '#include` statements here
// as this file is included multiple times into different namespaces
```

**Comment by lucasw** [comment]
https://github.com/lucasw/ros_comm/tree/zenoh_pub_sub_cpp

https://github.com/lucasw/ros_one2z/tree/zenoh_cpp_ros_comm

still getting multiple definition- though I was onto something with separated out api.hxx and impl.hxx includes but it still doesn't work.  Maybe put all the zenoh code into one cpp file?

**Comment by lucasw** [comment]
https://github.com/eclipse-zenoh/zenoh-cpp/pull/87 - works with latest zenoh_cpp_ros_comm- can run a C++ ros node using the modified ros_comm and publish an image that a zenoh python script receives

**Comment by lucasw** [comment]
ros::serialization::serializationLength(*image_msg) returns a proper value, but once inside Publisher::publish it returns a value too small by a factor of 10- something is lost with the templating?

**Comment by lucasw** [comment]
Saw in a presentation that zeno ros1 bridge can also replace roscore, would commingling that make doing things with this custom ros_comm work better?

**Comment by lucasw** [comment]
Need to add C++ subscriber support to ros_comm zenoh_pub_sub_cpp- rospy pub/sub works, and roscpp publishing, so this is the last thing (before diving into how to make rostopic/rosnode list etc. work, or just calling that good enough).

`ros_comm/clients/roscpp/include/ros/node_handle.h` subscribe() is the entry point.

**Comment by lucasw** [comment]
run ros_comm tests with zenoh modifications (also need to run on unmodified ros_comm to see if they were passing before)

```
catkin build --catkin-make-args run_tests
```

**Comment by lucasw** [comment]
https://github.com/cvilas/grape/tree/main/modules/common/ipc/examples has either copies or modified versions of the official examples, but also notes about how to use shared memory properly (need to configure it in config files).

> Modify the config on both publisher and subscriber to enable the shared memory transport
> On the publisher side, write into shared memory buffers created by the ShmManager (Changing config alone is not enough)
> On the subscriber side, nothing special was required other than modified config

**Comment by lucasw** [comment]
Need to manually add the zenoh library to this and everything- really need to export it properly:
```
/usr/bin/ld: CMakeFiles/message_filters-test_subscriber.dir/test/test_subscriber.cpp.o: undefined reference to symbol 'zc_shm_alloc'
```

Maybe just modify catkin to always provide it with catkin_LIBRARIES?  No not everything in C++ needs it, just roscpp users.

https://gitlab.kitware.com/cmake/cmake/-/issues/15415

**Comment by lucasw** [comment]
With https://github.com/lucasw/ros_from_src/issues/33 working can now fix any test that breaks because of zenoh changes, first one

```
/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/test/test_roscpp/test/src/subscribe_self.cpp: In function ‘void subscriberCallback(const ros::SingleSubscriberPublisher&, const ros::Publisher&)’:
/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/test/test_roscpp/test/src/subscribe_self.cpp:58:16: error: no matching function for call to ‘ros::Publisher::publish(test_roscpp::TestArray&) const’
   58 |     pub.publish(outmsg);
      |     ~~~~~~~~~~~^~~~~~~~
```

**Comment by lucasw** [comment]
Also 

```
[ 66%] Built target test_roscpp-subscribe_unsubscribe
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/tools/rostest/scripts/rostest", line 71, in <module>
    rostestmain()
  File "<string>", line 278, in rostestmain
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/tools/rostest/src/rostest/rostest_main.py", line 53, in <module>
    from rostest.rostest_parent import ROSTestLaunchParent
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/tools/rostest/src/rostest/rostest_parent.py", line 49, in <module>
    from rospy import logwarn
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/devel/lib/python3/dist-packages/rospy/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 49, in <module>
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/clients/rospy/src/rospy/client.py", line 62, in <module>
    import rospy.impl.rosout 
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/clients/rospy/src/rospy/impl/rosout.py", line 45, in <module>
    from rospy.topics import Publisher, Subscriber
  File "/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/clients/rospy/src/rospy/topics.py", line 105, in <module>
    from zenoh import Reliability, Sample
ModuleNotFoundError: No module named 'zenoh'
```

The catkin_make run_tests is inside a venv which has zenoh, is the test running outside of it?

**Comment by lucasw** [comment]
Go back to catkin build -maybe it runs inside venv

```
catkin build --catkin-make-args run_tests
```

**Comment by lucasw** [comment]
Need to install zenoh outside of the venv

```
zenoh-python$ cargo build --release
```

(not using `maturin` since that also needs to be pip installed)

**Comment by lucasw** [comment]
https://robotics.stackexchange.com/questions/101542/what-controls-the-python-search-path-and-how

**Comment by lucasw** [comment]
Maybe catkin workspaces could be made into proper python virtual environments, and every ros package with python would get pip installed (and then that would also be the solution all the setup.py warnings)?

**Comment by lucasw** [comment]
```
[ WARN] [1703980841.679638624 /test_subscriber ${shortfile}:190]: need to eliminate need for this copy
thread '<unnamed>' panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:26:
cannot access a Thread Local Storage value during or after destruction: AccessError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Testcase: testtest_subscriber] ... ok

[ROSTEST]-----------------------------------------------------------------------

[message_filters.rosunit-test_subscriber/simple][passed]
[message_filters.rosunit-test_subscriber/subUnsubSub][passed]
[message_filters.rosunit-test_subscriber/subInChain][passed]
[message_filters.rosunit-test_subscriber/singleNonConstCallback][FAILURE]-------
/home/lucasw/ros/ros1_ros_comm_catkin_make/src/ros_comm/utilities/message_filters/test/test_subscriber.cpp:156
Expected equality of these values:
  msg.get()
    Which is: 0x565400cd2640
  h.msg_.get()
    Which is: 0x565400cd2250
--------------------------------------------------------------------------------

[message_filters.rosunit-test_subscriber/multipleNonConstCallbacksFilterSubscriber][passed]
[message_filters.rosunit-test_subscriber/multipleCallbacksSomeFilterSomeDirect][passed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 6
 * ERRORS: 0
 * FAILURES: 1
```

**Comment by lucasw** [comment]
utilities/message_filters/test/test_message_filters_cache.py is hanging when run locally (23.04)

**Comment by lucasw** [comment]
Can't have `rospy.Subscriber(...)` and assume subscription exists until end of context- have to set it to a variable `sub = rospy.Subscriber(...)`

**Comment by lucasw** [comment]
rosbag tests are failing because bags written to `/tmp` aren't closed properly, all have `.active` postfix and need reindexing

**Comment by lucasw** [comment]
It looks like the rosbag .active issue only exists in when also using a custom rosconsole `ubuntu_2210` branch- make sure that is fully updated and look for any salsa debian patches

**Comment by lucasw** [comment]
This is the venv issue: https://github.com/ros/ros_comm/issues/2149

Looks like I can disable PythonPathOverride in my ros_comm fork, then don't have to do the above workaround of installing zenoh outside of pip (that will take some manual cleanup)

**Comment by lucasw** [comment]
Looks like default debian catkin adds cmake prefix path to the ros package path, which fouls up rosrust compilation:

```
Extending:          [cached] /home/lucasw/other/install:/home/lucasw/other/install/lib/cmake
```
